###网关服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-zuul
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka


### 配置网关反向代理
zuul:
  routes:
    api-a:
     ### 以 /app-weixin/访问转发到微信服务
      path: /app-weixin/**
      serviceId: app-weixin
    api-b:
        ### 以 /app-member/访问转发到会员服务
      path: /app-member/**
      serviceId: app-member

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

