
###服务启动端口号
server:
  port: 8800
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

spring:
  application:
    name:  app-point
###数据库相关连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.130:3306/meite-member?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
  ####连接地址
    host: 192.168.136.130
   ####端口号   
    port: 5672
   ####账号 
    username: guest
   ####密码  
    password: guest
    listener:
      simple:
        retry:
        ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
         ####最大重试次数
          max-attempts: 5
        ####重试间隔时间
          initial-interval: 1000ms
        ####开启手动ack  
        acknowledge-mode: manual 
        default-requeue-rejected: false

   
