
###服务启动端口号
server:
  port: 9900
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
spring:
  application:
    name:  app-seckill-consumer
###数据库相关连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.130:3306/meite-seckill?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
  ####连接地址
    host: 192.168.136.130
   ####端口号   
    port: 5672
   ####账号 
    username: guest
   ####密码  
    password: guest
    listener:
      simple:
        retry:
        ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
         ####最大重试次数
          max-attempts: 5
        ####重试间隔时间
          initial-interval: 1000ms
        ####开启手动ack  
        acknowledge-mode: manual 
        default-requeue-rejected: false
  redis:
    host: 192.168.136.130

   
##mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: Y
      logic-not-delete-value: N
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
