
###服务启动端口号
server:
  port: 9500
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka


  
spring:
  application:
    name:  app-auth
  zipkin:
      base-url: http://127.0.0.1:9411/
      ###全部采集
  sleuth:
     sampler:
      probability: 1.0
  redis:
    host: 192.168.136.130
###数据库相关连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.130:3306/meite-member?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
  ####连接地址
    host: 192.168.136.130
   ####端口号   
    port: 5672
   ####账号 
    username: guest
   ####密码  
    password: guest
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true 

##mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: Y
      logic-not-delete-value: N
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
